// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AutoRouterView: typeof import('./src/components/AutoRouterView.vue')['default']
    CalendarView: typeof import('./src/components/NoteViews/CalendarView.vue')['default']
    DialogEntryPreview: typeof import('./src/components/DialogEntryPreview.vue')['default']
    DialogGroupSelect: typeof import('./src/components/DialogGroupSelect.vue')['default']
    DialogIconEdit: typeof import('./src/components/DialogIconEdit.vue')['default']
    DialogInput: typeof import('./src/components/DialogInput.vue')['default']
    GlobalSettings: typeof import('./src/components/GlobalSettings.vue')['default']
    HistoryDialog: typeof import('./src/components/HistoryDialog.vue')['default']
    IconDisplay: typeof import('./src/components/IconDisplay.vue')['default']
    ListView: typeof import('./src/components/NoteViews/ListView.vue')['default']
    LunarDay: typeof import('./src/components/Calendar/LunarDay.vue')['default']
    MarkdownEditor: typeof import('./src/components/MarkdownEditor.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCollapseTransition: typeof import('naive-ui')['NCollapseTransition']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NModal: typeof import('naive-ui')['NModal']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NThing: typeof import('naive-ui')['NThing']
    NTree: typeof import('naive-ui')['NTree']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
